name: CI

on: [pull_request, workflow_call]

jobs:
  # TODO: add build-macos

  build-linux:
    name: Build wheels on Linux ${{ matrix.architecture }}

    runs-on: ununtu-latest

    strategy:
      matrix:
        include:
          - wheel_name: "mini-face-wheel-linux-manylinux_2_28_x86_64"
            architecture: "x86_64"
            container: ".github/containers/manylinux_x86_64.Dockerfile"
          # TODO: add linux_aarch64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          buildkitd-flags: --debug

      - name: Build Docker image
        # using build-push-action (without push) to make use of cache arguments
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.container }}
          tags: manylinux_${{ matrix.architecture }}:latest
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          BUILDKIT_PROGRESS: plain

      - uses: actions/checkout@v4

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.21.1

      - name: Store wheel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.wheel_name }}
          path: ./wheelhouse/*.whl
          compression-level: 0
