name: CI

on: [pull_request, workflow_call]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Debug
        run: |
          whereis g++
          whereis c++
          whereis gcc
          whereis clang

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11.5
        # Separate vcpkg installation procedure on Linux
        if: runner.os != 'Linux'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

      - name: Show obtained wheels and some debug info
        run: |
          ls ./dist
